### PR TITLE
Fix .options defaultValue

### LINKED ISSUE #74: args.option vs args.options, bug?
Hi!

So I have this simple script

```
var args = require('args');
var path = require('path');

var availableTypes = [
  'all',
  'products',
  'conversion-chart'
];

args.option('type', 'The type of index to update ('+ availableTypes.join(', ') +')');
/*
args.options([
  { name: 'type', description: 'The type of index to update ('+ availableTypes.join(', ') +')' }
]);
*/

args.examples([
  { usage: path.basename(__filename) + ' update --type all', description: 'Update all search indexes.' },
  { usage: path.basename(__filename) + ' update --type products --type conversion-chart', description: 'Update only 2 specific search indexes.' }
]);

var flags = args.parse(process.argv, {
  name: path.basename(__filename),
  version: false
});

console.log(flags);
```

When I call the script `scripts.js -t all`

I get this

`{ t: 'all', type: 'all' }`

Now if I comment the `args.option` and uncomment `args.options` and run it again, I get this :

`{ t: false, type: false }`

shouldn't that give the same results or am I missing something?

### PR DESCRIPTION
**Pull request by ntwcklng**
Test fails on current master branch.
Fixes #74

### CODE REVIEW

**Comment by leo** [comment]
Beautiful, thanks!

File: index.js [hunk 1]
```diff
@@ -65,7 +65,7 @@ class Args {
     }
 
     for (const item of list) {
-      const preset = item.defaultValue || false;
+      const preset = item.defaultValue || undefined;
```
Comment (TooTallNate) [inline index.js]: Why have the `|| undefined` here at all?

Comment (leo) [inline index.js]: @ntwcklng ^

Comment (ntwcklng) [inline index.js]: Thanks! Done in #78

**Comment by leo** [comment]
https://github.com/leo/args/releases/tag/2.4.2
